notifications:
  email: false
language: c
env:
  matrix:
  - BUILD_TYPE='doxygen'  BUILD_CATEGORY='doxygen'
  global:
    secure: KhV4pJR1xOFksX+ExDqqGi91R6t3oxtk5jzYu4Ii9nfWymu5DNCZXZu8C2GuTy+jhDeShSmqAVqTI6cMNCCOfo8KZmKEnWtjj/Dbp0jOTyYCfLTH0tjeYuLNoHFOwCnbcw+8QOEPr3aKC5vDKmiDNxU3KLsHOybnItMRGHJI1kYL163WSMAE67BZ9fTkaSZtP6XkHmkTEpE9vI/eZoOJk9F8ctEz27HxlA7ptdiPp1AsfCRiY6oGnDGkFQ+q05rNlIqtOJV5rmG//w+xUC0OIe0BxxL7vm+0rvITZd3ghCAuvTWoYBnRwu8+pH3vdchCk6ARJOooq/P4kAfHtEKNxs2OBAjewtNoCqm2Mj2o+iEZIvl/zSHh4Fn7nSx015v9XQ0ModbqnOxT+UXP+Qm0oehj5pmasG8q8+gsx1Y06MCUxJ7hb8CpBg+w3Ha8LUKnNIpDWoSjKOwFHumh1XItRz1f6XG9f/3KXMd8VZYTayGxQnAC9wgocgrvXvRsR+z9CjqP+x2OPO/HNwRS/Su8/Xjk7GfSagxQImNk5ny+bqWa4aAX6cTrawkMAWEiqSthNeDc74fmm3O5SrZkUs1iC+wBuZyUv3tl72fla2j781ZKNLSl76Yj0sN6BlhJ0RiA9VJKwp+JYcwfSFRQQgPeFMsHoDVt/azIk1Csn+eSjMI=
before_script:
- WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused
  --no-dns-cache --timeout 300"
- sudo apt-get -qq update
- export PROJ_ROOT=$(pwd)
- if [ ${BUILD_CATEGORY:-0} = doxygen ] ; then sudo add-apt-repository ppa:libreoffice/libreoffice-4-4
  -y && sudo apt-get -qq update && sudo apt-get --no-install-suggests --no-install-recommends
  -qq install doxygen  && doxygen --version ; fi
- sudo apt-get -qq install gcc-avr avr-libc
- sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386
  libstdc++6:i386
script:
- make -C tests/$BUILD_TYPE all
after_success:
- cd $PROJ_ROOT
- doxygen docs/Doxyfile > /dev/null
- ls ./docs
- chmod +x ./deploy-ghpages.sh
- cd docs/html
- git init
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "travis-ci"
- git add *
- git commit -m "Deployed to Github Pages"
- git push --force --quiet "https://${GH_TOKEN}@github.com/brtos/brtos.git" master:gh-pages
##- ./deploy-ghpages.sh
